/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SsoCallbackRouteImport } from './routes/sso-callback'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthedDashboardRouteImport } from './routes/_authed/dashboard'
import { Route as ApiWorkspacesImportRouteImport } from './routes/api/workspaces/import'
import { Route as ApiGithubReposRouteImport } from './routes/api/github/repos'
import { Route as AgentsSlugRegistrationDotjsonRouteImport } from './routes/agents/$slug/registration[.]json'
import { Route as AgentsSlugOasfDotjsonRouteImport } from './routes/agents/$slug/oasf[.]json'
import { Route as AgentsSlugMcpRouteImport } from './routes/agents/$slug/mcp'
import { Route as AgentsSlugA2aRouteImport } from './routes/agents/$slug/a2a'
import { Route as AuthedWorkspacesWorkspaceIdRouteImport } from './routes/_authed/workspaces/$workspaceId'
import { Route as AuthedRunsRunIdRouteImport } from './routes/_authed/runs/$runId'
import { Route as ApiWorkspacesWorkspaceIdSyncRouteImport } from './routes/api/workspaces/$workspaceId/sync'
import { Route as ApiWorkspacesWorkspaceIdRunsRouteImport } from './routes/api/workspaces/$workspaceId/runs'
import { Route as ApiWorkspacesWorkspaceIdPreviewLinkRouteImport } from './routes/api/workspaces/$workspaceId/preview-link'
import { Route as ApiRunsRunIdRefreshRouteImport } from './routes/api/runs/$runId/refresh'
import { Route as ApiRunsRunIdMessagesRouteImport } from './routes/api/runs/$runId/messages'
import { Route as ApiRunsRunIdAbortRouteImport } from './routes/api/runs/$runId/abort'
import { Route as AgentsSlugDotwellKnownAgentCardDotjsonRouteImport } from './routes/agents/$slug/[.]well-known/agent-card[.]json'

const SsoCallbackRoute = SsoCallbackRouteImport.update({
  id: '/sso-callback',
  path: '/sso-callback',
  getParentRoute: () => rootRouteImport,
} as any)
const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedDashboardRoute = AuthedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthedRoute,
} as any)
const ApiWorkspacesImportRoute = ApiWorkspacesImportRouteImport.update({
  id: '/api/workspaces/import',
  path: '/api/workspaces/import',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGithubReposRoute = ApiGithubReposRouteImport.update({
  id: '/api/github/repos',
  path: '/api/github/repos',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsSlugRegistrationDotjsonRoute =
  AgentsSlugRegistrationDotjsonRouteImport.update({
    id: '/agents/$slug/registration.json',
    path: '/agents/$slug/registration.json',
    getParentRoute: () => rootRouteImport,
  } as any)
const AgentsSlugOasfDotjsonRoute = AgentsSlugOasfDotjsonRouteImport.update({
  id: '/agents/$slug/oasf.json',
  path: '/agents/$slug/oasf.json',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsSlugMcpRoute = AgentsSlugMcpRouteImport.update({
  id: '/agents/$slug/mcp',
  path: '/agents/$slug/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsSlugA2aRoute = AgentsSlugA2aRouteImport.update({
  id: '/agents/$slug/a2a',
  path: '/agents/$slug/a2a',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedWorkspacesWorkspaceIdRoute =
  AuthedWorkspacesWorkspaceIdRouteImport.update({
    id: '/workspaces/$workspaceId',
    path: '/workspaces/$workspaceId',
    getParentRoute: () => AuthedRoute,
  } as any)
const AuthedRunsRunIdRoute = AuthedRunsRunIdRouteImport.update({
  id: '/runs/$runId',
  path: '/runs/$runId',
  getParentRoute: () => AuthedRoute,
} as any)
const ApiWorkspacesWorkspaceIdSyncRoute =
  ApiWorkspacesWorkspaceIdSyncRouteImport.update({
    id: '/api/workspaces/$workspaceId/sync',
    path: '/api/workspaces/$workspaceId/sync',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiWorkspacesWorkspaceIdRunsRoute =
  ApiWorkspacesWorkspaceIdRunsRouteImport.update({
    id: '/api/workspaces/$workspaceId/runs',
    path: '/api/workspaces/$workspaceId/runs',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiWorkspacesWorkspaceIdPreviewLinkRoute =
  ApiWorkspacesWorkspaceIdPreviewLinkRouteImport.update({
    id: '/api/workspaces/$workspaceId/preview-link',
    path: '/api/workspaces/$workspaceId/preview-link',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiRunsRunIdRefreshRoute = ApiRunsRunIdRefreshRouteImport.update({
  id: '/api/runs/$runId/refresh',
  path: '/api/runs/$runId/refresh',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRunsRunIdMessagesRoute = ApiRunsRunIdMessagesRouteImport.update({
  id: '/api/runs/$runId/messages',
  path: '/api/runs/$runId/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRunsRunIdAbortRoute = ApiRunsRunIdAbortRouteImport.update({
  id: '/api/runs/$runId/abort',
  path: '/api/runs/$runId/abort',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsSlugDotwellKnownAgentCardDotjsonRoute =
  AgentsSlugDotwellKnownAgentCardDotjsonRouteImport.update({
    id: '/agents/$slug/.well-known/agent-card.json',
    path: '/agents/$slug/.well-known/agent-card.json',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/sso-callback': typeof SsoCallbackRoute
  '/dashboard': typeof AuthedDashboardRoute
  '/runs/$runId': typeof AuthedRunsRunIdRoute
  '/workspaces/$workspaceId': typeof AuthedWorkspacesWorkspaceIdRoute
  '/agents/$slug/a2a': typeof AgentsSlugA2aRoute
  '/agents/$slug/mcp': typeof AgentsSlugMcpRoute
  '/agents/$slug/oasf.json': typeof AgentsSlugOasfDotjsonRoute
  '/agents/$slug/registration.json': typeof AgentsSlugRegistrationDotjsonRoute
  '/api/github/repos': typeof ApiGithubReposRoute
  '/api/workspaces/import': typeof ApiWorkspacesImportRoute
  '/agents/$slug/.well-known/agent-card.json': typeof AgentsSlugDotwellKnownAgentCardDotjsonRoute
  '/api/runs/$runId/abort': typeof ApiRunsRunIdAbortRoute
  '/api/runs/$runId/messages': typeof ApiRunsRunIdMessagesRoute
  '/api/runs/$runId/refresh': typeof ApiRunsRunIdRefreshRoute
  '/api/workspaces/$workspaceId/preview-link': typeof ApiWorkspacesWorkspaceIdPreviewLinkRoute
  '/api/workspaces/$workspaceId/runs': typeof ApiWorkspacesWorkspaceIdRunsRoute
  '/api/workspaces/$workspaceId/sync': typeof ApiWorkspacesWorkspaceIdSyncRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/sso-callback': typeof SsoCallbackRoute
  '/dashboard': typeof AuthedDashboardRoute
  '/runs/$runId': typeof AuthedRunsRunIdRoute
  '/workspaces/$workspaceId': typeof AuthedWorkspacesWorkspaceIdRoute
  '/agents/$slug/a2a': typeof AgentsSlugA2aRoute
  '/agents/$slug/mcp': typeof AgentsSlugMcpRoute
  '/agents/$slug/oasf.json': typeof AgentsSlugOasfDotjsonRoute
  '/agents/$slug/registration.json': typeof AgentsSlugRegistrationDotjsonRoute
  '/api/github/repos': typeof ApiGithubReposRoute
  '/api/workspaces/import': typeof ApiWorkspacesImportRoute
  '/agents/$slug/.well-known/agent-card.json': typeof AgentsSlugDotwellKnownAgentCardDotjsonRoute
  '/api/runs/$runId/abort': typeof ApiRunsRunIdAbortRoute
  '/api/runs/$runId/messages': typeof ApiRunsRunIdMessagesRoute
  '/api/runs/$runId/refresh': typeof ApiRunsRunIdRefreshRoute
  '/api/workspaces/$workspaceId/preview-link': typeof ApiWorkspacesWorkspaceIdPreviewLinkRoute
  '/api/workspaces/$workspaceId/runs': typeof ApiWorkspacesWorkspaceIdRunsRoute
  '/api/workspaces/$workspaceId/sync': typeof ApiWorkspacesWorkspaceIdSyncRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/sso-callback': typeof SsoCallbackRoute
  '/_authed/dashboard': typeof AuthedDashboardRoute
  '/_authed/runs/$runId': typeof AuthedRunsRunIdRoute
  '/_authed/workspaces/$workspaceId': typeof AuthedWorkspacesWorkspaceIdRoute
  '/agents/$slug/a2a': typeof AgentsSlugA2aRoute
  '/agents/$slug/mcp': typeof AgentsSlugMcpRoute
  '/agents/$slug/oasf.json': typeof AgentsSlugOasfDotjsonRoute
  '/agents/$slug/registration.json': typeof AgentsSlugRegistrationDotjsonRoute
  '/api/github/repos': typeof ApiGithubReposRoute
  '/api/workspaces/import': typeof ApiWorkspacesImportRoute
  '/agents/$slug/.well-known/agent-card.json': typeof AgentsSlugDotwellKnownAgentCardDotjsonRoute
  '/api/runs/$runId/abort': typeof ApiRunsRunIdAbortRoute
  '/api/runs/$runId/messages': typeof ApiRunsRunIdMessagesRoute
  '/api/runs/$runId/refresh': typeof ApiRunsRunIdRefreshRoute
  '/api/workspaces/$workspaceId/preview-link': typeof ApiWorkspacesWorkspaceIdPreviewLinkRoute
  '/api/workspaces/$workspaceId/runs': typeof ApiWorkspacesWorkspaceIdRunsRoute
  '/api/workspaces/$workspaceId/sync': typeof ApiWorkspacesWorkspaceIdSyncRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/sign-in'
    | '/sign-up'
    | '/sso-callback'
    | '/dashboard'
    | '/runs/$runId'
    | '/workspaces/$workspaceId'
    | '/agents/$slug/a2a'
    | '/agents/$slug/mcp'
    | '/agents/$slug/oasf.json'
    | '/agents/$slug/registration.json'
    | '/api/github/repos'
    | '/api/workspaces/import'
    | '/agents/$slug/.well-known/agent-card.json'
    | '/api/runs/$runId/abort'
    | '/api/runs/$runId/messages'
    | '/api/runs/$runId/refresh'
    | '/api/workspaces/$workspaceId/preview-link'
    | '/api/workspaces/$workspaceId/runs'
    | '/api/workspaces/$workspaceId/sync'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/sign-in'
    | '/sign-up'
    | '/sso-callback'
    | '/dashboard'
    | '/runs/$runId'
    | '/workspaces/$workspaceId'
    | '/agents/$slug/a2a'
    | '/agents/$slug/mcp'
    | '/agents/$slug/oasf.json'
    | '/agents/$slug/registration.json'
    | '/api/github/repos'
    | '/api/workspaces/import'
    | '/agents/$slug/.well-known/agent-card.json'
    | '/api/runs/$runId/abort'
    | '/api/runs/$runId/messages'
    | '/api/runs/$runId/refresh'
    | '/api/workspaces/$workspaceId/preview-link'
    | '/api/workspaces/$workspaceId/runs'
    | '/api/workspaces/$workspaceId/sync'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/sign-in'
    | '/sign-up'
    | '/sso-callback'
    | '/_authed/dashboard'
    | '/_authed/runs/$runId'
    | '/_authed/workspaces/$workspaceId'
    | '/agents/$slug/a2a'
    | '/agents/$slug/mcp'
    | '/agents/$slug/oasf.json'
    | '/agents/$slug/registration.json'
    | '/api/github/repos'
    | '/api/workspaces/import'
    | '/agents/$slug/.well-known/agent-card.json'
    | '/api/runs/$runId/abort'
    | '/api/runs/$runId/messages'
    | '/api/runs/$runId/refresh'
    | '/api/workspaces/$workspaceId/preview-link'
    | '/api/workspaces/$workspaceId/runs'
    | '/api/workspaces/$workspaceId/sync'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRoute: typeof AuthedRouteWithChildren
  SignInRoute: typeof SignInRoute
  SignUpRoute: typeof SignUpRoute
  SsoCallbackRoute: typeof SsoCallbackRoute
  AgentsSlugA2aRoute: typeof AgentsSlugA2aRoute
  AgentsSlugMcpRoute: typeof AgentsSlugMcpRoute
  AgentsSlugOasfDotjsonRoute: typeof AgentsSlugOasfDotjsonRoute
  AgentsSlugRegistrationDotjsonRoute: typeof AgentsSlugRegistrationDotjsonRoute
  ApiGithubReposRoute: typeof ApiGithubReposRoute
  ApiWorkspacesImportRoute: typeof ApiWorkspacesImportRoute
  AgentsSlugDotwellKnownAgentCardDotjsonRoute: typeof AgentsSlugDotwellKnownAgentCardDotjsonRoute
  ApiRunsRunIdAbortRoute: typeof ApiRunsRunIdAbortRoute
  ApiRunsRunIdMessagesRoute: typeof ApiRunsRunIdMessagesRoute
  ApiRunsRunIdRefreshRoute: typeof ApiRunsRunIdRefreshRoute
  ApiWorkspacesWorkspaceIdPreviewLinkRoute: typeof ApiWorkspacesWorkspaceIdPreviewLinkRoute
  ApiWorkspacesWorkspaceIdRunsRoute: typeof ApiWorkspacesWorkspaceIdRunsRoute
  ApiWorkspacesWorkspaceIdSyncRoute: typeof ApiWorkspacesWorkspaceIdSyncRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sso-callback': {
      id: '/sso-callback'
      path: '/sso-callback'
      fullPath: '/sso-callback'
      preLoaderRoute: typeof SsoCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/dashboard': {
      id: '/_authed/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthedDashboardRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/api/workspaces/import': {
      id: '/api/workspaces/import'
      path: '/api/workspaces/import'
      fullPath: '/api/workspaces/import'
      preLoaderRoute: typeof ApiWorkspacesImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/github/repos': {
      id: '/api/github/repos'
      path: '/api/github/repos'
      fullPath: '/api/github/repos'
      preLoaderRoute: typeof ApiGithubReposRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents/$slug/registration.json': {
      id: '/agents/$slug/registration.json'
      path: '/agents/$slug/registration.json'
      fullPath: '/agents/$slug/registration.json'
      preLoaderRoute: typeof AgentsSlugRegistrationDotjsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents/$slug/oasf.json': {
      id: '/agents/$slug/oasf.json'
      path: '/agents/$slug/oasf.json'
      fullPath: '/agents/$slug/oasf.json'
      preLoaderRoute: typeof AgentsSlugOasfDotjsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents/$slug/mcp': {
      id: '/agents/$slug/mcp'
      path: '/agents/$slug/mcp'
      fullPath: '/agents/$slug/mcp'
      preLoaderRoute: typeof AgentsSlugMcpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents/$slug/a2a': {
      id: '/agents/$slug/a2a'
      path: '/agents/$slug/a2a'
      fullPath: '/agents/$slug/a2a'
      preLoaderRoute: typeof AgentsSlugA2aRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/workspaces/$workspaceId': {
      id: '/_authed/workspaces/$workspaceId'
      path: '/workspaces/$workspaceId'
      fullPath: '/workspaces/$workspaceId'
      preLoaderRoute: typeof AuthedWorkspacesWorkspaceIdRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/runs/$runId': {
      id: '/_authed/runs/$runId'
      path: '/runs/$runId'
      fullPath: '/runs/$runId'
      preLoaderRoute: typeof AuthedRunsRunIdRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/api/workspaces/$workspaceId/sync': {
      id: '/api/workspaces/$workspaceId/sync'
      path: '/api/workspaces/$workspaceId/sync'
      fullPath: '/api/workspaces/$workspaceId/sync'
      preLoaderRoute: typeof ApiWorkspacesWorkspaceIdSyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/workspaces/$workspaceId/runs': {
      id: '/api/workspaces/$workspaceId/runs'
      path: '/api/workspaces/$workspaceId/runs'
      fullPath: '/api/workspaces/$workspaceId/runs'
      preLoaderRoute: typeof ApiWorkspacesWorkspaceIdRunsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/workspaces/$workspaceId/preview-link': {
      id: '/api/workspaces/$workspaceId/preview-link'
      path: '/api/workspaces/$workspaceId/preview-link'
      fullPath: '/api/workspaces/$workspaceId/preview-link'
      preLoaderRoute: typeof ApiWorkspacesWorkspaceIdPreviewLinkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/runs/$runId/refresh': {
      id: '/api/runs/$runId/refresh'
      path: '/api/runs/$runId/refresh'
      fullPath: '/api/runs/$runId/refresh'
      preLoaderRoute: typeof ApiRunsRunIdRefreshRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/runs/$runId/messages': {
      id: '/api/runs/$runId/messages'
      path: '/api/runs/$runId/messages'
      fullPath: '/api/runs/$runId/messages'
      preLoaderRoute: typeof ApiRunsRunIdMessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/runs/$runId/abort': {
      id: '/api/runs/$runId/abort'
      path: '/api/runs/$runId/abort'
      fullPath: '/api/runs/$runId/abort'
      preLoaderRoute: typeof ApiRunsRunIdAbortRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents/$slug/.well-known/agent-card.json': {
      id: '/agents/$slug/.well-known/agent-card.json'
      path: '/agents/$slug/.well-known/agent-card.json'
      fullPath: '/agents/$slug/.well-known/agent-card.json'
      preLoaderRoute: typeof AgentsSlugDotwellKnownAgentCardDotjsonRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthedRouteChildren {
  AuthedDashboardRoute: typeof AuthedDashboardRoute
  AuthedRunsRunIdRoute: typeof AuthedRunsRunIdRoute
  AuthedWorkspacesWorkspaceIdRoute: typeof AuthedWorkspacesWorkspaceIdRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedDashboardRoute: AuthedDashboardRoute,
  AuthedRunsRunIdRoute: AuthedRunsRunIdRoute,
  AuthedWorkspacesWorkspaceIdRoute: AuthedWorkspacesWorkspaceIdRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
  SignInRoute: SignInRoute,
  SignUpRoute: SignUpRoute,
  SsoCallbackRoute: SsoCallbackRoute,
  AgentsSlugA2aRoute: AgentsSlugA2aRoute,
  AgentsSlugMcpRoute: AgentsSlugMcpRoute,
  AgentsSlugOasfDotjsonRoute: AgentsSlugOasfDotjsonRoute,
  AgentsSlugRegistrationDotjsonRoute: AgentsSlugRegistrationDotjsonRoute,
  ApiGithubReposRoute: ApiGithubReposRoute,
  ApiWorkspacesImportRoute: ApiWorkspacesImportRoute,
  AgentsSlugDotwellKnownAgentCardDotjsonRoute:
    AgentsSlugDotwellKnownAgentCardDotjsonRoute,
  ApiRunsRunIdAbortRoute: ApiRunsRunIdAbortRoute,
  ApiRunsRunIdMessagesRoute: ApiRunsRunIdMessagesRoute,
  ApiRunsRunIdRefreshRoute: ApiRunsRunIdRefreshRoute,
  ApiWorkspacesWorkspaceIdPreviewLinkRoute:
    ApiWorkspacesWorkspaceIdPreviewLinkRoute,
  ApiWorkspacesWorkspaceIdRunsRoute: ApiWorkspacesWorkspaceIdRunsRoute,
  ApiWorkspacesWorkspaceIdSyncRoute: ApiWorkspacesWorkspaceIdSyncRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
